pipeline {
    agent any

    environment {

        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
       
        TF_PLAN_FILE          = 'tfplan'
    }

    stages {
        stage('Terraform Init') {
            steps {
                bat 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                bat "terraform plan -out=${env.TF_PLAN_FILE}"
            }
        }

        stage('Manual Approval') {
            when {
                branch 'main'
            }
            steps {
                input message: "Please review the Terraform Plan in the console output. Proceed with Apply?", ok: "Proceed"
            }
        }

        stage('Terraform Apply') {
            when {
                branch 'main'
            }
            steps {
                bat "terraform apply -auto-approve ${env.TF_PLAN_FILE}"
            }
        }
    }

    post {
        always {
            echo "Cleaning up workspace..."
            deleteDir()
        }
        success {
            echo "Infrastructure deployment/validation successful!"
        }
        failure {
            echo "Infrastructure deployment/validation failed. Check the logs."
        }
    }
}