pipeline {
    agent any

    options {
        ansiColor('xterm')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        TF_PLAN_FILE          = 'tfplan'
    }

    stages {
        stage('Terraform Init') {
            steps {
                // Tell Jenkins to go into the project folder
                dir('aws-S3') {
                    bat 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('aws-S3') {
                    bat "terraform plan -out=${env.TF_PLAN_FILE}"
                }
            }
        }

        stage('Manual Approval') {
            when {
                branch 'main'
            }
            steps {
                input message: "Review Plan? Proceed with Apply?", ok: "Proceed"
            }
        }

        stage('Terraform Apply') {
            when {
                branch 'main'
            }
            steps {
                dir('aws-S3') {
                    bat "terraform apply -auto-approve ${env.TF_PLAN_FILE}"
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up workspace..."
            deleteDir()
        }
    }
}